spring:
  thymeleaf:
    mode: HTML5
    content-type: text/html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/static/

server:
  port: 8083



